global:
  scrape_interval: ${PROMETHEUS_SCRAPE_INTERVAL}
  evaluation_interval: ${PROMETHEUS_EVALUATION_INTERVAL}

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - ${PROMETHEUS_TARGET_ALERTMANAGER_HOST}

rule_files:
  - "rules/*.yaml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["${PROMETHEUS_TARGET_HOST}"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["${PROMETHEUS_TARGET_NODE_EXPORTER_HOST}"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["${PROMETHEUS_TARGET_CADVISOR_HOST}"]

  - job_name: "postgres"
    static_configs:
      - targets: ["${PROMETHEUS_TARGET_POSTGRES_EXPORTER_HOST}"]

  - job_name: "traefik"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["${PROMETHEUS_TARGET_TRAEFIK_HOST}"]

  - job_name: "frontend"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["${PROMETHEUS_TARGET_FRONTEND_HOST}"]
